include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude:
    # exclude json_serialize generated file
    - lib/data/api/entity/*.g.dart
    # exclude Chopper generated file
    - lib/data/api/*.chopper.dart
    # exclude Mockito generated file
    - test/*.mocks.dart